### PR TITLE
Fix some more warnings from GCC

### PR DESCRIPTION
**Pull request by taketwo**

### CODE REVIEW

**Comment by acki-m** [comment]
What compiler or warning level do you have?
In travis with gcc I don't see these warnings.

PS: Thanks for you help!

**Comment by taketwo** [comment]
Actually, I just realized that these warnings show up only for the CUDA parts of my project, i.e. the files compiled with NVCC. (But in fact, NVCC is just a wrapper around GCC.)

How to reproduce:

```cpp
// test.cu
#include <rttr/type>
#include <rttr/registration>
int main(int argc, const char** argv)
{
  return 0;
}
```

Compile with: `nvcc test.cu -I/path/to/rttr/include -std=c++11`

**Comment by acki-m** [comment]
When you find out how to adjust the gcc compiler settings via travis, so that I can these warning also in the CI, this would be very helpful.

**Comment by taketwo** [comment]
I can not find a way to get a warning about unreachable statements. GCC used to have `-Wunreachable-code` option, but [it's defunct](https://gcc.gnu.org/ml/gcc-help/2011-05/msg00360.html) for a long time now. Clang also has this option, but does not report anything.

I tried to compile my code that uses RTTR with Clang and `-Wall -Wextra`, and it reveals a great deal of assorted warnings (`-Wmismatched-tags`, `-Wpessimizing-move`, `-Wunused-local-typedef`, `-Wunused-parameter`, `-Wunused-variable`). Give it a try!

**Pull request merged**
