### PR TITLE
Conan package

### PR DESCRIPTION
**Pull request by weatherhead99**
I have ported my previous conan package to the newer version and in source build.
I have tested it so far on linux and OSX. 

I will try and get to testing on windows, I won't have an opportunity for a week or so, you may want to hold off accepting until then, but if not the PR is here.

### CODE REVIEW

**Comment by weatherhead99** [comment]
@acki-m  either way is possible, I already maintain out of repo conan packages for rttr (https://github.com/weatherhead99/rttr-conan ) . The conan project states that in repository is the "ideal" if upstream wants it but separate repository if not

**Comment by acki-m** [comment]
@weatherhead99 
Okay, I prefer to have a separate repo for conan, so we can better test it with travis and appveyor (where you can provide the build scripts there then too).
Can you please give me a PR, with the necessary changes (c165920) in RTTR, and another one here:
https://github.com/rttrorg/conan-rttr for conan?

**Comment by weatherhead99** [comment]
ok, there are a few questions then. What I suggest is the following:
1) I do a PR on this repo for the one tiny cmakelists.txt patch needed (c165920)
2) you release a new version
3) we release a conan package in your repo

Currently for 0.9.5 my package works ok. The changes to the package for 0.9.6 are substantial. But for an "out of source" package, it has to fetch the source from somewhere. This can either be from a git checkout or a tarball. I much prefer a tarball, as then the user doesn't get the entire repo history downloaded every time they build the package.  So I'd much rather do a separate package once a new tarball is available somewhere. Unless you want to mirror the source into the conan-rttr repo and do an "in source" package? It's up to you entirely, I don't mind. I can also provide in that PR appveyor and travis files to test the package.

**Comment by acki-m** [comment]
What do you mean with point 3?
A conan package in my repo? You mean this one `.py` file? What is the advantage for getting accepted to conan-center?
You know you can specify with: `--depth` the git history during checkout? I do this during CI builds.

**Comment by weatherhead99** [comment]
there would be conanfile.py, the contents of test_package and CI scripts. Conan-center is the only repository enabled by default for everyone who installs conan. If your package is in there, it's immediately available to conan users without much further searching. By "your repo", I mean one owned by you as the rttr developer rather than one owned by me. 

Thanks for the tip :-) I'm happy to do it from git, but still think tarball is preferred.

**Comment by acki-m** [comment]
That is the point. The testing of conan package should be done in an extra repo.
So we might get better CI performance, it already takes ages to compile RTTR for the various compilers.
including the poco test might increase this time.
I am okay, with using the tar file.

So you have to tell me, what do I have to do besides setting the tag. Do I not have to build all the binaries for the various systems? Or even upload the source code in the tar archive?

**Comment by weatherhead99** [comment]
the binary packages for some systems get built (and uploaded) by the CI once the package is in "stable" mode. For other systems, it'll get built when the user installs it, if there isn't a matching binary already on bintray. 

All that is missing right now is a source tarball to build from. So just tag it and throw up a tarball somewhere and I will finish off the package.

**Comment by acki-m** [comment]
Why can the test package not be in the extra repo, I created? https://github.com/rttrorg/conan-rttr
The only file that should be here is the `conanfile.py`, as far as I understand.

**Comment by acki-m** [comment]
@weatherhead99 
Can you update the PR, so I can merge it.

**Comment by acki-m** [comment]
@weatherhead99 
I would like to merge today, because the version is almost ready. Can you please update the PR today?

**Comment by weatherhead99** [comment]
This PR is now unnecessary. Since you want a separate package, the only change needed to rttr itself was in the other PR which you already accepted. 

So, I will close this, and will prepare a PR for your separate conan package repo _after_ the new version is released (this will allow me to test it on my end, make sure the source is fetched properly etc.

Hope that is ok

**Pull request closed without merging**
