### PR TITLE
correct install path for libraries -> lib instead of bin

### PR DESCRIPTION
**Pull request by gabyx**
Self explaining I think, or should the libraries really go into the bin folder?

### CODE REVIEW

**Comment by acki-m** [comment]
Yes, it has to be.
Otherwise the applications cannot be executed (like the examples or bench tools, or even unit_tests)

**Comment by gabyx** [comment]
dont understand, because on linux and macos mostly we put the library in /lib 
is that thing here not putting them in /bin?
```
install(TARGETS rttr_core EXPORT rttr_targets
                RUNTIME DESTINATION ${RTTR_BIN_INSTALL_DIR}
                LIBRARY DESTINATION ${RTTR_BIN_INSTALL_DIR}
                ARCHIVE DESTINATION ${RTTR_LIB_INSTALL_DIR})
```
I think one should rather,  edit the "rpath" in the executable, I think cmake handles that (its kind of complicated) when installing . Mostly the user anyway does not want to install the tests/benchmarks (maybe the examples)?
https://cmake.org/Wiki/CMake_RPATH_handling

**Comment by gabyx** [comment]
I think its very related to #101 ...

**Comment by gabyx** [comment]
same as #103

**Pull request closed without merging**
