### PR TITLE
bug in array_range<>::begin() functions

### PR DESCRIPTION
**Pull request by sbalogh**
I updated to the latest git version. When executed my crazy test program again, I got a crash in the update_class_list function. I recognized if the array_range<> is empty and it have a predicate then there is a crash in the array_range<>::begin() function.
Everything works fine, after applying my patch.

### CODE REVIEW

**Comment by acki-m** [comment]
please upload your test program, so I can see why it is failing.
Regarding this, `is _pointer`, just use [type::is_pointer](http://www.rttr.org/doc/master/classrttr_1_1type.html#ae31c9ee6ca22898a8853dfde804a3bc6)

```
my_prop.get_type().is_pointer()
```

Maybe I will remove this `is_array` function is property, it is redundant.

**Comment by sbalogh** [comment]
The reason why I added `is_pointer` function to property class is that when I register a "big class" property with  `bind_as_ptr` policy the new  `my_prop.is_pointer()` return false ( `my_prop.get_type().is_pointer()` return true), so I know the "real type of the big class property" at runtime. If the real type is not a pointer then I never use set_value with (for example) a pointer to derived class or do not use destructor.
Maybe it is hackish and ugly. It would be fine to have an ability to query bind policy or "real type" of property at runtime.   

I will upload my hasty test program as soon as possible.
Thanks for your work!

**Comment by acki-m** [comment]
I think, returning the binding policy is a better way, instead of adding an `is_pointer`  function. So your second thought is better.
And btw. maybe I should also add another policy to properties, return the property encapsulated in a `std::reference_wrapper`. Then you know it is a wrapped type, and can do other kind of things.
Anyway, please upload your "crazy" test case. So I can actually see what is going on.

**Comment by sbalogh** [comment]
Here is my test program. I made it for internal use, so do not expect much, but does its job. :) 
[test.zip](https://github.com/rttrorg/rttr/files/243555/test.zip)

**Pull request closed without merging**
