### PR TITLE
Fix installation on Linux/Mac machines

### PR DESCRIPTION
**Pull request by Warchant**
- [x] Resolve CMP0042 issue with new CMake, OSX
- [x] Make CMAKE_DEBUG_POSTFIX rewritable from terminal (e.g.: `cmake .. -DCMAKE_DEBUG_POSTFIX=hello`)
- [x] Add manually generated `detail/base/version.h`: if you install this project and do not include it via generated `rttr-config.cmake`, then this file is not generated and compilation fails
- [x] Use `GNUInstallDirs` package for install paths on OSX and Linux. Now you can write 
   ```bash
   cmake -DCMAKE_INSTALL_PREFIX=/usr/local ${src}
   make install
   ```
   and it will install libraries into `/usr/local/lib`, binaries in `/usr/local/bin`, cmake in `/usr/local/share/rttr/cmake`
- [x] Fix issue with permissions: typically on OSX or Linux you want to install libraries in `/usr/local/lib`, binaries in `/usr/local/bin`, etc. To write in these directories you need root permissions. In CMake, during install, it installed `OWNER_READ` permissions on headers, it resulted in permission error for other users - they were unable to read headers.
- [x] Replace legacy `libstdc++` with `libc++`

Now `master` can be built and installed in the system without any problems.

### CODE REVIEW

**Comment by acki-m** [comment]
> Add manually generated detail/base/version.h: if you install this project and do not include it via generated rttr-config.cmake, then this file is not generated and compilation fails

This is not true. When you generate the cmake project, then this file will be generated from cmake.
When you install RTTR , it will be installed too. It's independent from ` rttr-config.cmake`.

I have to check first how your changes affect the VS-Windows build.

**Comment by acki-m** [comment]
I compiled your PR with MSVC, it fails because of this reason:
```
7>-- Install configuration: "Debug"
7>CMake Error at cmake_install.cmake:31 (file):
7>  file cannot create directory: C:/Program Files/rttr/share/rttr/cmake.
7>  Maybe need administrative privileges.
```
Can you restore the old behavior, so that by default, when not custom install directory was provided, it will be installed in the build directory?

**Comment by gabyx** [comment]
I am working an a fix for this!

**Comment by gabyx** [comment]
See PR #103 : I merged this PR, and restored some good behavior which was over written.
The version.h, is written on OS X and I did not merge this add. file

**Comment by Warchant** [comment]
Sorry for the long answer. Since @gabyx already fixed issues, I will close this PR and will continue work in #103

**Pull request closed without merging**
