### PR TITLE
Remove OWNER_READ permission from cmake files. (fixes #147)

### LINKED ISSUE #147: Consider removing "PERMISSIONS OWNER_READ" in CMake install commands
The *.cmake files in the CMake/ folder use "PERMISSIONS OWNER READ" for the install command.
This is problematic because when you do e.g. "sudo make install" to "/usr/local" the files will be only "rw-------" and not usable by a normal user.

Is there any reason for these permissions? If not I would suggest removing this option to get "rw-r--r--" (or whatever the umask is configured to).

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

This PR remove unnecessary OWNER_READ permission in cmake files, and fixes #147

### CODE REVIEW

**Comment by acki-m** [comment]
When you give me a good reason to make it writable say so. Otherwise it will stay. There is a reason why I am doing this.

**Comment by krop** [comment]
If you need a reason, here's one. the headers are unusable for building kdenlive because the rttr headers can't be opened by distributions' build system.

**Comment by lbeltrame** [comment]
To elaborate more, the files when installed system wide, like any Linux distribution does, are readable only by root. This means that no other user can access them, making anything depending on rttr unbuildable.

**Comment by soroshsabz** [comment]
@acki-m As you can see in #147 @Ghabry says a reason for this

**Comment by awilfox** [comment]
As noted in #147 the goal is WORLD_READ, not removing permission keyword.

Would you consider changing the PR?  Or would you like me to submit a PR with this change instead?

**Comment by soroshsabz** [comment]
@awilfox as you can see in [CMake documentation](https://cmake.org/cmake/help/latest/command/install.html#installing-files)  

> Files installed by this form are by default given permissions OWNER_WRITE, OWNER_READ, GROUP_READ, and WORLD_READ if no PERMISSIONS argument is given

So for to care the worries of @acki-m I added `OWNER_READ GROUP_READ WORLD_READ` in `PERMISSIONS` option.

**Comment by soroshsabz** [comment]
@acki-m I change only CMakeLists.txt files, why code coverage change?

**Comment by soroshsabz** [comment]
@awilfox Did you can review this PR?

thanks :)

**Comment by awilfox** [comment]
Looks fine to me.

**Comment by soroshsabz** [comment]
@acki-m any update?

thanks :)

**Pull request merged**
