### PR TITLE
self explaining...

### PR DESCRIPTION
**Pull request by gabyx**
some cmake errors...

### CODE REVIEW

**Comment by acki-m** [comment]
Cannot be merged, windows build will fails.
You have to check against: `WIN32`

**Comment by gabyx** [comment]
travis now has autocancelation =) how awesome .-)

**Comment by acki-m** [comment]
@gabyx 
What is autocancelation? It will cancel all following builds, when the first one fails?

**Comment by gabyx** [comment]
it cancles automatically other pushes, if a more recent is currently on the top build list :-)

**Pull request merged**
